name: Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute static analysis
        run: composer analyze:ci
      - name: Execute tests
        run: composer test:ci
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0-beta.2
        if: always()
        with:
          files: "test-reports/**/*.xml"
